"""
app/models/retention_time_series.py
─────────────────────────────────────
Daily retention snapshots for each user×topic pair.
Enables retention trend charts, forgetting velocity calculation,
and ML training data generation.

Write pattern: One row per user×topic per day,
generated by the daily aggregation background job.
"""

import uuid
from datetime import date

from sqlalchemy import Date, Float, ForeignKey, Index, Integer, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.database.base import Base


class RetentionTimeSeries(Base):
    __tablename__ = "retention_time_series"
    __table_args__ = (
        UniqueConstraint(
            "user_id", "topic_id", "snapshot_date",
            name="uq_rts_user_topic_date",
        ),
        Index("ix_rts_user_topic_date", "user_id", "topic_id", "snapshot_date"),
        Index("ix_rts_date", "snapshot_date"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )
    topic_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("topics.id", ondelete="CASCADE"),
        nullable=False,
    )
    snapshot_date: Mapped[date] = mapped_column(Date, nullable=False)
    retention_score: Mapped[float] = mapped_column(Float, nullable=False)
    stability_score: Mapped[float] = mapped_column(Float, nullable=False)
    decay_rate: Mapped[float] = mapped_column(Float, nullable=False)
    revision_count: Mapped[int] = mapped_column(Integer, nullable=False)
    days_since_last_revision: Mapped[float | None] = mapped_column(
        Float, nullable=True
    )

    def __repr__(self) -> str:
        return (
            f"<RetentionTimeSeries user={self.user_id} topic={self.topic_id} "
            f"date={self.snapshot_date} retention={self.retention_score:.3f}>"
        )
